### ISSUE TITLE
Extraction des actes au delà des délibérations

### ISSUE THREAD

**Issue by ElodieTessier** [megalis-bretagne/opendata-extraction#13]
En plus des délibérations, les collectivités souhaitent également retrouver tous les autres catégories d'actes qui passent par le contrôle de légalité.

**Comment by lvinsonneau** [comment]
Pour info, proposition faite à la DGCL et qui rassemblerait les besoins des collectivités (**en attente de leur retour**) : 
. pour les **actes réglementaires** : on mettrait dans ce cas l'option de **publication à OUI par défaut** (a priori c'est cohérent avec les objectifs des obligations du 1er juillet)

. pour les **actes individuels** : on mettrait dans ce cas l'option de publication à **NON par défaut** (ex. des délégations de signatures, qui pourraient être statuées à "oui" car conforme RGPD)

. pour les actes **"autres"** : on mettrait dans ce cas l'option de publication à **NON par défaut** (difficile de savoir ce que les collectivités y rangent vraiment, donc par principe de précaution, on mettrait "non")

**Comment by yguenneugues** [comment]
**Configuration pastell**

- Modification des flux studio ( actes réglementaires, actes individuels et autres)
- Création ou réutilisation du connecteur existant ( ged-megalis-opendata-auto-delib)
⁉⁉ problématique pour avoir différentes valeur par défaut : _Pastell ne permet pas de mettre une valeur par défaut. Nous avions utilisé "un hack" pour le faire dans le cas des délibération, clef:valeur avec clef =0 (OUI) comme valeur par défaut. Comment faire pour avoir une autre valeur par défaut ?_
- Association en masse du connecteur pour l'ensemble des id_e

Modification code Extraction

Prise en compte / adaptation des règles de gestion concernant le code acte nature ( Actes réglementaires ,Autres et Actes individuels  )

| libellé                             | CodeNatureActe |
|-------------------------------------|----------------|
| Délibérations                       | 1              |
| Actes réglementaires                | 2              |
| Actes individuels                   | 3              |
| Contrats,conventions et avenants    | 4              |
| Documents budgétaires et financiers | 5              |
| Autres                              | 6              |
