### ISSUE TITLE
Format de sortie de l' API STATS

### ISSUE THREAD

**Issue by spelhate** [megalis-bretagne/opendata-extraction#17]
Actuellement les API retournent leurs résultats au format csv, ce qui est limitant pour un réemploi en dev. JSON est le parfait complément pour faciliter la réutilisation de ces API.
Je propose donc de rendre négociable le format de sortie via l'ajout d'un paramètre d'URL - **format**:

- csv : valeur par défaut
- json

exemple d'appel avec ce nouveau paramètre https://data-api.megalis.bretagne.bzh/api/v1/scdl/deliberation/233500016/2021/json

**Comment by lvinsonneau** [comment]
@spelhate : c'est OK pour toi en pré-prod ?

**Comment by spelhate** [comment]
> @spelhate : c'est OK pour toi en pré-prod ?

Il y a eu une PR ? J'ai dû rater l'info.
Du coup je ne sais pas comment tester car je ne vois pas le paramètre dans swagger

![image](https://user-images.githubusercontent.com/1793792/195648071-ded277a2-ff6b-4ab1-997a-efe2566eb4fa.png)

**Comment by spelhate** [comment]
Ha si trouvé mais pour les statistiques.

![image](https://user-images.githubusercontent.com/1793792/195648727-73fd1dbf-565b-4c10-9211-66707ad89fb6.png)

**Comment by spelhate** [comment]
Testé avec cette URL : https://data-api-preprod.megalis.bretagne.bzh/api/v1/stats/publications?startDate=2022-09-01&endDate=2022-09-31&mode=json

ce qui donne : 
```json
[
  {
    "combo pastell": "oui",
    "etat": "publié",
    "nature acte": "Autres",
    "nombre": 29
  },
  {
    "combo pastell": "oui",
    "etat": "publié",
    "nature acte": "déliberation",
    "nombre": 9
  },
  {
    "combo pastell": "oui",
    "etat": "publié",
    "nature acte": "budget",
    "nombre": 3
  },
  {
    "combo pastell": "oui",
    "etat": "non publié",
    "nature acte": "Autres",
    "nombre": 1
  },
  {
    "combo pastell": "oui",
    "etat": "publié",
    "nature acte": "Autres",
    "nombre": 1
  },
  {
    "combo pastell": "ne sais pas",
    "etat": "non publié",
    "nature acte": "Autres",
    "nombre": 1
  }
]
```

**Comment by lvinsonneau** [comment]
@spelhate : la question est : est-ce que la demande d'origine d'extension du format de sortie au json n'avait d'intérêt que pour les stats ? Ou est-ce que l'on n'étend pas aux données elles-mêmes ?

**Comment by spelhate** [comment]
La demande d'origine concernait les actes plutôt que les stats. Cf description de l'issue. Il me semble que par la suite le libellé de l'issue a été modifié pour circonscrire l'évolution aux seules stats suite à un point avec l'équipe projet.

**Comment by spelhate** [comment]
De mon point de vu, je trouve intéressant de pouvoir récupérer dans un format json les actes. Faut-il faire une nouvelle issue  ou ne pas clore celle ci ?
