### ISSUE TITLE
SCDL Délibérations - Présence de ligne avec un SIREN à 0

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-extraction#18]
Dans l'extraction du fichier SCDL délibérations sur data.gouv.fr au 30/06/2022 (https://www.data.gouv.fr/fr/datasets/deliberations-des-organismes-adherents-de-megalis-bretagne/), 9 lignes sont avec un SIREN à 
![2022-06-30 10_57_00-Window](https://user-images.githubusercontent.com/2498403/176636623-b8d67497-a13c-442f-b5d9-e956e0765e1a.png)
0

**Comment by yguenneugues** [comment]
ça vient de pastell, 
nous avons 1 organisme  avec un siren =0 et un autre avec siren = 123456789

**Comment by yguenneugues** [comment]
Tous les siren à 0 ont été corrigé dans pastell le 06/07/22. (Plus de nouveau cas)
Les données open data qui avaient été poussées avec ces SIREN à 0 sont corrigées
