### ISSUE TITLE
API Stats - Lignes redondantes ou "bizarres" dans ​/stats​/publications

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-extraction#19]
Extraction via https://data-api.megalis.bretagne.bzh/doc/ sur les publications ce jour (30/06/2022
[stats_publications.csv](https://github.com/megalis-bretagne/opendata-extraction/files/9018147/stats_publications.csv)
)

Le fichier csv extrait a quelques bizarreries : 

- code 3
- lignes redondantes 'ex. "budget - 3 - publié)
- lignes dont la présence est suspecte (ex. budget à "non" ou "ne sait pas" puisque a priori l'utilisateur Pastell ne peut pas renseigner ces valeurs)

**Comment by yguenneugues** [comment]
Prise en compte des nouvelles nature d''actes et installé en prod
