### ISSUE TITLE
Problème ordre affichage des actes / annexes

### ISSUE THREAD

**Issue by yguenneugues** [megalis-bretagne/opendata-extraction#20]
cf https://github.com/megalis-bretagne/opendata-marqueblanche/issues/20$

**Comment by lvinsonneau** [comment]
à voir ici : https://data-preprod.megalis.bretagne.bzh/?siren=253514491
@ElodieTessier : bon pour toi aussi ? on passe en prod ?

**Comment by ElodieTessier** [comment]
@lvinsonneau oui c'est tout bon !
