### ISSUE TITLE
Problème sur API statistiques concernant les taux de non publication

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-extraction#22]
Je viens de relever les statistiques sur l'API. Elles ont beaucoup évoluer en peu de temps.
Beaucoup de collectivités sont à plus de 50% de taux de non publication. 
cf. exemple sur la cartographie des communes en image jointe : 
![image](https://user-images.githubusercontent.com/2498403/185400135-8491a037-0a00-4354-9363-52c3ff5dc94b.png) et dans le fichier csv que je viens d'extraire (https://nextcloud.megalis.bretagne.bzh/s/pTnDEbTAWrKQrNQ)

N'y-a-t-il pas un problème un problème dans le calcul ?

**Comment by lvinsonneau** [comment]
Si je prends l'exemple de la commune de Parigné qui utilise la marque-blanche (http://parigne.fr/parigne-CM.html). 

- dans l'outil de publication opendata : 159 actes en tout, dont 11 au statut "non publié"
- dans le CSV issu de l'API stats : 148 publié / 159 non publié (51.7915% de non publication)

**Comment by gautierrog** [comment]
Ca doit être corrigé maintenant

**Comment by lvinsonneau** [comment]
oui effectivement, merci @gautierrog !
![image](https://user-images.githubusercontent.com/2498403/185558517-963cf5c0-3019-4a39-ac57-a3b6b4780506.png)
