### ISSUE TITLE
Problème sur API statistiques concernant les services désactivés

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-extraction#23]
L'**API stats** est à vérifier pour les extractions sur les "**services désactivés**".
En effet, je viens de faire l'extraction et j'y trouve le SIREN 245614383 (Questembert communauté).

Or la marque-blanche est bien fonctionnelle https://data.megalis.bretagne.bzh/?siren=245614383

**Comment by clemoigno** [comment]
Bonjour @lvinsonneau ! La stats est OK, la fonctionnalité a bien été désactivée par Questembert Communauté (dommage).
Le problème c'est que la marque blanche ne tien pas compte de cela, et ça, c'est un problème (en cours de traitement par @gautierrog ).

La désactivation de ce service me pose par ailleurs question : Quid des données déjà publiées (sur marque blanche, sur data-gouv), si la collectivité désactive la publication ? On désactive "à partir de maintenant et jusque réactivation potentielle" ? Ou on retire toutes les publications de la collectivité en question, y compris les publications passées ?

**Comment by gautierrog** [comment]
J'ai mis à jour la marque blanche pour qu'elle n'affiche plus les documents des collectivités qui ont désactivées la publication. On ne retrouve donc plus les documents de Questembert dans la marque blanche

**Comment by lvinsonneau** [comment]
OK merci à vous deux !
Pour moi, on reste sur ce paramétrage "radical" : soit la collectivité souhaite publier et elle peut aller dans la finesse de "je publie ou non" via le module de gestion de publication. Soit elle ne souhaite pas publier et auquel cas, il faut assumer qu'il n'y ait plus rien (même si on est d'accord, c'est obligatoire, mais elle en est responsable...). C'est mon avis, mais c'est ouvert à la discussion @spelhate @Cridard @ElodieTessier

**Comment by clemoigno** [comment]
Actuellement 8 SIREN sont concernés par la désactivation du service.
Suite au correctif de @gautierrog , on ne trouve plus rien concernant 7 des 8 SIREN (ce qui signifie que soit ces SIREN avaient désactivé le service d'emblée -- comme Questembert visiblement --, soient ils n'ont jamais rien publié).

Sur les 8 il n'en reste plus qu'un pour lequel des données sont toujours visible : Commune de Saint-Gilles (SIREN 213502750).
Dans la marque blanche, on voit des données jusqu'au 5 juillet. 
Le service a du être désactivé ensuite. 

Du coup, suite au correctif de @gautierrog , on ne voit plus les publication postérieures au 5 juillet.
Par contre, on voit toujours celles antérieures.

J'espère que mon explication est claire.
On attend votre retour pour savoir si on désactive en mode tout ou rien comme tu le suggères @lvinsonneau .

**Comment by lvinsonneau** [comment]
OK, on en recausera tous ensemble. Mais oui, c'est très clair !

**Comment by spelhate** [comment]
> Actuellement 8 SIREN sont concernés par la désactivation du service. Suite au correctif de @gautierrog , on ne trouve plus rien concernant 7 des 8 SIREN (ce qui signifie que soit ces SIREN avaient désactivé le service d'emblée -- comme Questembert visiblement --, soient ils n'ont jamais rien publié).
> 
> Sur les 8 il n'en reste plus qu'un pour lequel des données sont toujours visible : Commune de Saint-Gilles (SIREN 213502750). Dans la marque blanche, on voit des données jusqu'au 5 juillet. Le service a du être désactivé ensuite.
> 
> Du coup, suite au correctif de @gautierrog , on ne voit plus les publications postérieures au 5 juillet. Par contre, on voit toujours celles antérieures.
> 
> J'espère que mon explication est claire. On attend votre retour pour savoir si on désactive en mode tout ou rien comme tu le suggères @lvinsonneau .

Le mode rien implique de supprimer ce qui a déjà été publié par la collectivité sur data.gouv.fr ?

**Comment by clemoigno** [comment]
On publie sur data.gouv chaque jour une regénération complète des données. Pas le différentiel. Donc si les données sont 'annulées' dans notre outil, elles disparaitront automatiquement du SCDL à la MAJ suivante, le lendemain.

**Comment by spelhate** [comment]
Merci @clemoigno ça simplifie les choses.

**Comment by ElodieTessier** [comment]
OK, merci à vous pour ces précisions et ce nouveau fonctionnement.

**Comment by gautierrog** [comment]
Les correctifs sur l'api des stats est livré en production.
