### ISSUE TITLE
Prise en compte acte sans tdt

### ISSUE THREAD

**Issue by yguenneugues** [megalis-bretagne/opendata-extraction#24]
- ajouter en bdd la prise en compte de nature_autre_detail
- ajouter dans solr l'info
- Dans l'ihm gérer la nature d'acte = 7   => Hors Préfecture
-Ajouter dans lexport format scdl all actes la colonne nature_autre_detail et la nouvelle nature

**Comment by yguenneugues** [comment]
- [ ] gestion Hors Préfecture dansl'ihm data-publication
- [ ] Export scdl acte colonne nature_autre_detail et la nouvelle nature
- [ ]  ajouter dans solr l'info
- [ ] ajouter en bdd mysql la prise en compte de nature_autre_detail

**Comment by yguenneugues** [comment]
installé en preprod

**Comment by spelhate** [comment]
Premier retour.
Outil de publication -> Ok
Marque blanche : il manque l'item "Hors préfecture" dans la liste déroulante permettant de filtrer les actes
API -> NATURE_ACTE = "7" -> OK
API -> NATURE_AUTRE_DETAIL -> KO car vide.
