### ISSUE TITLE
Mise en place d'un outil de monitoring

### ISSUE THREAD

**Issue by lvinsonneau** [megalis-bretagne/opendata-extraction#26]
Comme évoqué lors des points de suivi de projet, et dans la suite d'un incident que nous avions eu (arrêt des mises à jour quotidiennes sur data.gouv signalées par une collectivité), serait-il possible de mettre en place un outil de monitoring de la chaine de publication opendata.
Merci d'avance.

**Comment by lvinsonneau** [comment]
à étudier @spelhate + @yguenneugues : peut-on regarder les métadonnées du wget sur data.gouv sur les 3 jeux de données sur data.gouv (sont-ils publiés tous les jours O/N) ?

**Comment by yguenneugues** [comment]
@spelhate Exemple pour les délibération

Vérification au niveau du jeu de donnée :
- GET sur l'url : https://www.data.gouv.fr/api/2/datasets/60645c94e2bfd21cdc16c0be/
- Vérification que la dernière dans de modification est inférieur à 24 h , champ : last_modified

On peut aussi faire ça au niveau des ressources pour vérifier les anciens fichier
