### ISSUE TITLE
Création d'une API pour lister par siren les documents publiés

### ISSUE THREAD

**Issue by spelhate** [megalis-bretagne/opendata-extraction#30]
Avec l'objectif de superviser la "bonne publication" des documents en opendata, il est nécessaire de disposer d'une API publique retournant les infos suivantes : numero_de_lacte, objet, date_de_lacte...

**Comment by gautierrog** [comment]
https://data-publication.megalis.bretagne.bzh/private_api/doc/

voir `/publication/search/light`
