### ISSUE TITLE
Traitements des actes HORS délibérations créés depuis WEBDELIB pour passage dans le circuit OPENDATA

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-extraction#32]
Bonjour,

l'outil WEBDELIB gère 2 menus pour le traitement des ACTES : 
1 - un menu pour les délibérations qui permet de cocher l'option de passage par la GED (connecteur utilisé chez Megalis pour le workflow des publications)

2 - un menu "Autres actes" qui ne permet pas de cocher l'option de passage par la GED , et donc d'enchainer sur le workflow des publications.
Pour le traitement de ce dernier cas, il avait été évoqué de voir ce que donnait le passage d'un acte par le dossier pastell ls-actes-publication et voir ce qui pourrait en être fait pour l'injecter dans le circuit de publicatuin
Exemple de dossiers créées dans ls-actes-publication : 
https://pastell.megalis.bretagne.bzh/Document/detail?id_d=6bPTO0y&id_e=116
![image](https://user-images.githubusercontent.com/97181939/217522463-62aaf458-47e8-4d1f-b7b9-113bf30add42.png)

A discuter...

Ci-joints les 2 fichiers json et csv de ce flux

[V_AR_2022_401.zip](https://github.com/megalis-bretagne/opendata-extraction/files/10685656/V_AR_2022_401.zip)

**Comment by spelhate** [comment]
ça vaut le coup d'évaluer la faisabilité de cette évolution. Comment intégrer dans notre stack opendata Pastell les flux **ls-publication**. avec leur spécificité ?

**Comment by lvinsonneau** [comment]
avantage du flux ls-publication : données votants présentes
inconvénient : perd les annexes

**Comment by lvinsonneau** [comment]
piste : utiliser les scripts Pastell pour détecter actes automatiques (tous les jours ou toutes les semaines) et on les remet à l'état "SEND GED"

**Comment by spelhate** [comment]
Est-on sûr que côté Webdelib (version récente) , il n'est pas possible de cocher l'option de passage par la GED ?
