### ISSUE TITLE
fichier des délibérations 2023  certaines lignes avec nom de collectivité non renseigné

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-extraction#36]
Bonjour,

dans le fichier des délibérations de 2023 (exemple : celui téléchargé le 11/04/2023) 51 lignes (sur 34887) n'ont pas de nom de collectivité renseigné : 
il s'agit de ligne avec ces 3 sirets où le code NIC est à  tort à "00000": 
21220188300000
20004295000000
20008590000000

![image](https://user-images.githubusercontent.com/97181939/231224279-7f0e3521-d49e-4ace-9f08-05cae3a8b6eb.png)

**Comment by gautierrog** [comment]
J'ai corrigé les établissements avec le nic à '00000'

**Comment by Cridard** [comment]
Bonjour @gautierrog , j'ai généré le fichier des delib 2023 avec l'api sur https://data-api.megalis.bretagne.bzh/doc/,ça m'a l'air bon. merci. du coup je suppose que ça sera bon sur data.gouv demain, c'est ça?

**Comment by gautierrog** [comment]
Oui. Tout à fait.

**Comment by Cridard** [comment]
je te confirme @gautierrog  que c'est tout bon!merci
