### ISSUE TITLE
Fichiers DECP publiés dur data.gouv.fr sans déclaration xml

### ISSUE THREAD

**Issue by spelhate** [megalis-bretagne/opendata-extraction#37]
Depuis la MEP du 11/04/2023 les fichiers xml publiés sur data.gouv.fr ne comportent plus de déclaration xml.

Auparavant nous avions : 
```xml
<?xml version='1.0' encoding='utf8'?>
```

Avec la MEP d'hier nous aurions dû avoir : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
```

Finalement nous n'avons plus **aucune déclaration.**

A noter que l'API DECP retourne  la bonne déclaration : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
```

**Comment by gautierrog** [comment]
Je force désormais la declaration xml lors de l'export des DECP. C'est en preprod.

**Comment by lvinsonneau** [comment]
@syji35 : peux-tu valider la mise en prod pour clore cette issue stp ? Merci.

**Comment by syji35** [comment]
Vu sur le code au commit : https://github.com/megalis-bretagne/opendata-extraction/commit/5970b6b163d56eabddd75b9e465f85dc0e8a0d0f

Vu sur data.gouv.fr, les fichiers xml ont bien une déclaration XML
