### ISSUE TITLE
Delibération - DATES_AR

### ISSUE THREAD

**Issue by gautierrog** [megalis-bretagne/opendata-extraction#38]
Lors de la réunion:

- Schema invalide pour les delibs, il manque la DATE_PREFS notament.
- Prendre la date_ar du flux pastell?
- Pour tous les actes?

**Comment by lvinsonneau** [comment]
Petite précisions : 

- il s'agit du champ **PREF_DATE** dans le SCDL de destination
-  @yguenneugues  : **merci de nous confirmer si nous pouvons bien alimenter automatiquement ce champ** (à partir de date_ar) ?
- même si cela ne sera pas visible au niveau de data.gouv puisque le SCDL ne recouvre que le périmètre des délibérations, nous avons acté de **capitaliser cette date pour TOUS les actes.**

**Comment by gautierrog** [comment]
Nous prenons en compte le champ `date_ar` pour tous les flux bien configurés (-> https://github.com/orgs/megalis-bretagne/projects/2#card-89186777)
le scdl delibs prend en compte cette `date_ar`

**Comment by lvinsonneau** [comment]
@gautierrog : tu veux dire que c'était déjà le cas précédemment mais que les flux n'étaient pas bien configurés ou que vous avez fait une évolution ?

**Comment by spelhate** [comment]
> @gautierrog : tu veux dire que c'était déjà le cas précédemment mais que les flux n'étaient pas bien configurés ou que vous avez fait une évolution ?

@lvinsonneau  seules deux collectivités bénéficient actuellement de cette nouvelle configuration (Atelier de vendredi). Etape nécessaire pour valider les nouveaux paramétrages + nouvelle méthode de déploiement / mise à jour des connecteurs.

**Comment by lvinsonneau** [comment]
OK super, c'est que ça marche, vous nous direz quand la MEP est prévue. Merci !

**Comment by gautierrog** [comment]
Bonjour,

Oui, c'est un bug qui nous empêchait d'avoir les PREF_DATE d'exportée pour au delà d'un certain nombre de délibérations.

J'ai publié un hotfix et relancé un export des délibérations pour 2023. On retrouve maintenant les PREF_DATE de renseignées dans nos exports.

**Comment by lvinsonneau** [comment]
merci @gautierrog . C'est OK sur export data.gouv du jour à partir des données publiées en mai 2023. Je clos le ticket
