### ISSUE TITLE
Prise en charge complet du format date iso 8601

### ISSUE THREAD

**Issue by spelhate** [megalis-bretagne/opendata-extraction#39]
Des documents actes automatiques ne peuvent être publiés en open data car le format de la date n'est pas géré dans la chaîne d'extraction. En effet, le format date pris en charge actuellement est le suivant : "2023-05-30". Or certains documents ont la date au format "20230530" également conforme iso 8601 mais qui n'est pas pris en charge par la chaîne de traitement.

**Comment by syji35** [comment]
Corrigé" avec l'upgrade python
