### ISSUE TITLE
Recherche utilisateur

### ISSUE THREAD

**Issue by Cridard** [megalis-bretagne/opendata-extraction#45]
En étant connecté avec le compte SA.chrystele, la recherche suivante tombe en échec  :  

![Image](https://github.com/megalis-bretagne/opendata-extraction/assets/97181939/6408daeb-388f-45e8-9eb1-2c8ab077fe11)

![Image](https://github.com/megalis-bretagne/opendata-extraction/assets/97181939/7d57d050-8320-412f-92ce-2938be39d258)

Et avec un seul critères,exemple, une recherche par identifiant, la recherche aboutit

**Comment by PierreNicolas** [comment]
Correctif apporté à la recherche // sur l'identifiant et le courriel.
