### ISSUE TITLE
Budget: support du format CFU

### ISSUE THREAD

**Issue by gautierrog** [megalis-bretagne/opendata-extraction#51]
Suite au ticket iTop.

Ajouter le support des Compte Financier Unique comme une alternative aux comptes administratif au sein de la marque blanche.

**Comment by gautierrog** [comment]
Dans les flux de CFU, nous avons des lignes budgetaires sans direction (recette / depenses). Ce sont des informations indispensables pour la création de graphe. J'ai sollicité Laurent pour savoir quoi faire de ces données.

**Comment by ElodieTessier** [comment]
Url : https://data-publication.megalis.bretagne.bzh/budgets/public/ANNEE/SIRET/cfu

Recette OK, je passe le ticket à Done et je le clôture. Merci
