### ISSUE TITLE
Mise en place d'une API stats

### ISSUE THREAD

**Issue by yguenneugues** [megalis-bretagne/opendata-extraction#7]
API stats
1. Stats sur les publications =>Type d'acte  / Choix dans pastell  /  Etat / nombre
2. Stats du taux de non publication => Siren / nb oui / nb non / tauxDeNonPublié
3. Stats liste des siren qui ont  désactivé le service => Siren / open_data_active=non

**Comment by lvinsonneau** [comment]
+1

**Comment by yguenneugues** [comment]
![image](https://user-images.githubusercontent.com/10934427/156754004-796ac9f0-b50f-49d2-afb5-9960d7b846b8.png)

**Comment by yguenneugues** [comment]
installé en prod

**Comment by spelhate** [comment]
Merci @yguenneugues

**Comment by lvinsonneau** [comment]
Merci @yguenneugues  : y-aurait-il moyen d'ajouter un critère temporel afin de stocker les stats dans le temps (ex. tous les mois) ?

**Comment by ElodieTessier** [comment]
Merci @yguenneugues !
